### ISSUE TITLE
Error: DownloadHandler has already been destroyed

### ISSUE THREAD

**Issue by EmilieHK** [rwth-acis/VIAProMa#106]
The updateMRTKdevelop branch contains the upgraded project with the newer MRTK 2.4.0 version. As a result of this error the issue and project shelf do not load. This seems to be a known problem in the prerelease version of the MRTK 2.4.0 (https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7823). However, that version is not currently being used on the branch.

## How to recreate
In the project on the updateMRTKdevelop branch, open the Main Menu cube by clicking the main button. Then either try to open the issue or projects shelfs. The error will appear and the shelf will load forever.

**Comment by BenediktHensen** [comment]
The MRTK update changed the way that the Rest class administers the downloaded content: By default, the DownloadHandler is destroyed at an early stage since the MRTK assumes that the downloaded content will not be accessed. The calls in the `Rest` class, e.g. `Rest.GetAsync` now have a new argument `readResponseData` at the end which must be set to `true` if the downloaded content will later be accessed.

I updated the calls to the Rest class, e.g. `Rest.GetAsync(uri)` to `Rest.GetAsync(uri, null, -1, null, true). This fills the second to fourth arguments with their default values and the final `true` is the new flag which states that the content will be accessed later. This prevents the destruction of the DownloadHandler. Setting the argument to true is only necessary if the content is later accessed by calling the `ResponseBody` property of the response.
