### ISSUE TITLE
Requirement Bazaar projects can't be opened and a lot can't be found

### ISSUE THREAD

**Issue by SebastianMeinberger** [rwth-acis/VIAProMa#405]
**Describe the bug**
When opening a requirement bazaar project, a 500er Server error will appear for most projects and no requirements will load. The reason for this is that in the getProjects method from [RequirementsBazaar.cs](https://github.com/rwth-acis/VIAProMa/blob/fd7ec96d0baf1711f41facd1dc25c77fea0fb529/Frontend/VIAProMa/Assets/Scripts/WebConnection/RequirementsBazaar.cs) wrong name/project id combinations are retrived.
A lot of the found ids either don't exist at all or are aissigned to different projects. The found names also often don't exist or can't be read with the current credentials. Additionally, most public projects are never retrived at all, not even with a wrong id, e.g. from the project [A.I.Team](https://beta.requirements-bazaar.org/projects/44) neither name nor id is ever found.

Examples of retrived name/id combinations that are wrong
1. name: About page, id: 38 (id 38 actually belongs to [eLearning Collaboration](https://beta.requirements-bazaar.org/projects/38). A project named About page doesn't exist or is not public)
2. name: Covid-19 Online Self Declaration Portal, id: 467 (id 467 doesn't exist or belongs to a private project. The project Covid-19 Online Self Declaration does exist and is public, but its id is 67)

I assume that these problems arise from the recent changes in the Requirement Bazaar.

**To Reproduce**
1. Open a room
2. Open the issue shelf
3. Type into the Project field: "Covi"
4. Select "Covid-19 Online Self Declaration Portal" from the auto comletion list
5. Press the checkmark button. A 500er error will  occure since the retrived id is wrong.
6.  Type into the Project field: "Agile"
7.  Press the checkmark button. Nothing will happen, since this project wasn't found in the retriving phase despite it existing (https://beta.requirements-bazaar.org/projects/40) and it being public

**Expected behavior**
All projects I have acess too should be correctly retrived and suggested to me in the project autocompletion. Projects I don't have access too shouldn't be suggested too me. When I open an existing project I have acess too, all its requirements should be loaded and displayed on Issue Cards.

**Bug Observed on the Following Devices**
Check applicable devices and platform by putting an x in-between the square brackets.
- [x] Unity editor
- [ ] HoloLens 1
- [ ] HoloLens 2
- [ ] HTC VIVE
- [ ] Smartphone
- [ ] Other:

**Comment by SebastianMeinberger** [comment]
The base URL used in VIAProMa seems to be out of date. VIAProMa tries to access the Baazar via http://cloud17.dbis.rwth-aachen.de:8080/resources/requirementsBazaar but as far as I can tell, the API of the current instance is accesible via https://beta.requirements-bazaar.org/bazaar . When using https://beta.requirements-bazaar.org/bazaar/projects/ to retrive the projects, only correct combinations are retrived. Or is it on purpose that VIAProMa tries to access another instance than the [official](https://beta.requirements-bazaar.org/) one @BenediktHensen ? Not that I change this and VIAProMa does stuff on an instance we are not supposed to mess with.

**Comment by BenediktHensen** [comment]
The frontend of VIAProMa does not directly access the Requirements Bazaar but its own backend which is under cloud17. The backend, in turn, sends a request to the Requirements Bazaar's API. This architecture was created so that the frontend does not have to distinguish between different data types for representing issues. The backend takes the answers of the APIs and converts them into a generic task data format which is then sent to the frontend. This way, you can mix Requirements Bazaar and GitHub issues together with any future expansions and the visualizations still work as they extract the relevant information from the generic data format.

The backend accesses https://requirements-bazaar.org which is the address that the official version uses. https://beta.requirements-bazaar.org is a preview beta version where new features are tested before being pushed. I would assume that the beta version uses a separate database which would explain the differences in results.

The code 500 error messages are produced in VIAProMa's backend and are only propagated to the frontend. The Requirement Bazaar's API was recently changed where some fields were added to the JSON answer. In VIAProMa's backend, there are classes which define the expected JSON response format by the Requirements Bazaar. However, I think they are missing an attribute which tells them to ignore any further fields in the JSON response. Hence, the conversion from JSON to the class instance fails as it finds unexpected new JSON fields.
