### ISSUE TITLE
Update MRTK

### ISSUE THREAD

**Issue by danielbekhter** [rwth-acis/VIAProMa#80]
Raycasting in order to determine a controller's pointer position for gaze sharing would become unnecessary (see [here](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Input/Pointers.html#pointer-event-interfaces)). Handling global events would become easier and more efficient (see RegisterHandler vs Register [here](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Updating.html)).

**Comment by EmilieHK** [comment]
The updateMRTKdevelop Branch contains the upgraded project with the newer MRTK 2.4 version. After the initial error fixes, the following problems are still occurring and have to be solved.

- [ ] Error: _DownloadHandler has already been destroyed_ - as a result the issue and projects shelf do not load.

- [ ] Error: _transform.position assign attempt for 'visualizationName' is not valid. Input position is {NaN, NaN, NaN}_ - Visualizations cannot be dragged or otherwise moved from the shelf without this error. When already placed in the scene, visualizations are movable.
